#!/usr/bin/env python3
"""
Script to extract and analyze CSI data from log files generated by srsRAN
"""

import os
import sys
import csv
import argparse
import numpy as np
from pathlib import Path
from datetime import datetime


def parse_csi_file(filepath):
    """Parse a CSI log file and return structured data"""
    csi_data = []
    
    try:
        with open(filepath, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                csi_data.append(row)
    except Exception as e:
        print(f"Error reading {filepath}: {e}", file=sys.stderr)
        return []
    
    return csi_data


def analyze_csi(csi_data):
    """Analyze CSI data and print statistics"""
    if not csi_data:
        print("No CSI data found")
        return
    
    print(f"Total CSI samples: {len(csi_data)}")
    
    # Extract RNTIs
    rntis = set(row.get('rnti', '') for row in csi_data if row.get('rnti'))
    print(f"Unique RNTIs: {sorted(rntis)}")
    
    # Extract frequency information
    prbs = [int(row.get('nof_prb', 0)) for row in csi_data if row.get('nof_prb')]
    if prbs:
        print(f"PRB range: {min(prbs)} - {max(prbs)}")
        print(f"Average PRBs: {np.mean(prbs):.2f}")
    
    # Extract power measurements
    rsrp_values = [float(row['rsrp_db']) for row in csi_data 
                   if row.get('rsrp_db') and row['rsrp_db']]
    if rsrp_values:
        print(f"RSRP range: {min(rsrp_values):.2f} - {max(rsrp_values):.2f} dB")
        print(f"Average RSRP: {np.mean(rsrp_values):.2f} dB")
    
    # Extract CSI values
    csi_real = [float(row['csi_real']) for row in csi_data 
                if row.get('csi_real') and row['csi_real']]
    csi_imag = [float(row['csi_imag']) for row in csi_data 
                if row.get('csi_imag') and row['csi_imag']]
    
    if csi_real and csi_imag:
        csi_complex = [complex(r, i) for r, i in zip(csi_real, csi_imag)]
        csi_magnitude = [abs(c) for c in csi_complex]
        csi_phase = [np.angle(c) for c in csi_complex]
        
        print(f"CSI magnitude range: {min(csi_magnitude):.4f} - {max(csi_magnitude):.4f}")
        print(f"CSI phase range: {min(csi_phase):.4f} - {max(csi_phase):.4f} radians")


def export_to_numpy(csi_data, output_file):
    """Export CSI data to NumPy format for analysis"""
    # Extract CSI values
    csi_real = []
    csi_imag = []
    metadata = []
    
    for row in csi_data:
        if row.get('csi_real') and row.get('csi_imag'):
            csi_real.append(float(row['csi_real']))
            csi_imag.append(float(row['csi_imag']))
            metadata.append({
                'timestamp': row.get('timestamp', ''),
                'slot': int(row.get('slot', 0)),
                'symbol': int(row.get('symbol', 0)),
                'rnti': int(row.get('rnti', 0)),
                'prb': int(row.get('nof_prb', 0)),
            })
    
    if csi_real and csi_imag:
        csi_complex = np.array([complex(r, i) for r, i in zip(csi_real, csi_imag)])
        np.savez(output_file, 
                 csi=csi_complex,
                 metadata=metadata)
        print(f"Exported CSI data to {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Extract and analyze CSI data from srsRAN log files'
    )
    parser.add_argument('log_dir', 
                       help='Directory containing CSI log files',
                       default='/tmp/csi_logs',
                       nargs='?')
    parser.add_argument('--analyze', '-a',
                       action='store_true',
                       help='Analyze CSI data and print statistics')
    parser.add_argument('--export', '-e',
                       help='Export CSI data to NumPy format (specify output file)')
    parser.add_argument('--pattern', '-p',
                       default='csi_*.csv',
                       help='File pattern to match (default: csi_*.csv)')
    
    args = parser.parse_args()
    
    log_dir = Path(args.log_dir)
    if not log_dir.exists():
        print(f"Error: Log directory {log_dir} does not exist", file=sys.stderr)
        sys.exit(1)
    
    # Find all CSI log files
    csi_files = list(log_dir.glob(args.pattern))
    if not csi_files:
        print(f"No CSI log files found in {log_dir} matching pattern {args.pattern}")
        sys.exit(1)
    
    print(f"Found {len(csi_files)} CSI log file(s)")
    
    # Parse all files
    all_csi_data = []
    for csi_file in sorted(csi_files):
        print(f"Processing {csi_file.name}...")
        data = parse_csi_file(csi_file)
        all_csi_data.extend(data)
    
    if args.analyze:
        analyze_csi(all_csi_data)
    
    if args.export:
        export_to_numpy(all_csi_data, args.export)
    
    if not args.analyze and not args.export:
        print(f"Parsed {len(all_csi_data)} CSI samples from {len(csi_files)} file(s)")
        print("Use --analyze to see statistics or --export to save in NumPy format")


if __name__ == '__main__':
    main()

